### ISSUE TITLE
The FEN parser appears to fail somewhat often

### ISSUE THREAD

**Issue by santiweight** [functionalley/BishBosh#3]
CallStack (from HasCallStack):
  error, called at src-lib/BishBosh/Property/ForsythEdwards.hs:53:28 in bishbosh-0.0.0.6-BJyh4PHJCCLKyc1E1mTpYQ:BishBosh.Property.ForsythEdwards
BishBosh.Property.ForsythEdwards.readFEN:       failed to parse "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1".

Hope I'm not missing something obvious. The parser appears to reject any FEN that includes an en passant square. Parsing the following works for me:

   "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1"

Note I'm on 0.0.6 if it matters

**Comment by santiweight** [comment]
As a side note, I noticed that the PGN parser appears to expect much of the headers that can be included in a PGN. For example, "1. e4" is not accepted as a valid PGN. This seems to me quite a narrow view.

Thanks for the great package - I'm happy to contribute to either of these issues if you'll accept the PR. Also as a side note - is the choice of polyparse a purposeful one? The errors are quite obtuse (in comparison to say Mega/Attoparsec) and the api for polyparse, for example, is very minimal and lastly the project is no longer maintained. I'd be happy to contribute to some migration to a more modern library if wanted. I see that there is also a parsec option, but that libary has similar issues (last commit was August of 2019).

**Comment by functionalley** [comment]
Thanks for you valued comments.

The reason for **Polyparse** is that other parsers (e.g. Parsec) typically return **Either ParseError a**, which can't be constructed until all input data has been parsed; i.e. the parser doesn't produce data. When the input file is large, this uses too much RAM. I left the compilation-time option of **Parsec** because the errors were occasionally superior to Polyparse, & having the option of another parser allows one to be tested against the other.

I'll have a look at the other parser issues shortly & perhaps enlist your help.

**Comment by functionalley** [comment]
Regarding the parsing of **PGN**, it isn't the lack of **PGN**-tags that the parser rejects but the undefined game-result (See '**8.1.1.7: The Result tag' in https://www.chessclub.com/help/pgn-spec**).
So whilst "**1.e3**" fails to parse, "1.e3 *" succeeds by merely stating that the game is unfinished.

**bishbosh** uses some **PGN**-tags to annotate any move-hints requested by the player.
The set of tags used is configurable, see **options/ioOptions/pgnOptions/identificationTag** in the canned XML configuration-files.
This set of tags is concatenated to form a composite identifier for an archived game.
Any configured tags which aren't defined for an archived game, are silently replaced by a null string.

**Comment by functionalley** [comment]
I've fixed a bug in the parsing of **FEN** which occurred when an en-passant destination was defined, & implemented the option to use Extended Position Description too.
